version: '3'

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
  database:
    external: false
  
services:
  api:
    build:
      context: ../back-end/Inlog.Desafio.Backend
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ./api.env
    ports:
      - 5080:80
    networks:
      - database
      - backend
  database:
    image: mongo
    restart: always
    env_file:
      - ./mongo.env
    # ports:
    #   - 27017:27017
    networks:
      - database
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    env_file:
      - ./express.env
    networks:
      - database